"use client"

import type React from "react"
import { createContext, useContext, useState, type ReactNode } from "react"

interface LanguageContextType {
  language: "fr" | "ar"
  isRTL: boolean
  setLanguage: (lang: "fr" | "ar") => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}

// Translations
const translations = {
  fr: {
    // Common
    "common.loading": "Chargement...",
    "common.error": "Erreur",
    "common.success": "Succès",
    "common.cancel": "Annuler",
    "common.save": "Enregistrer",
    "common.delete": "Supprimer",
    "common.edit": "Modifier",
    "common.add": "Ajouter",
    "common.create": "Créer",
    "common.close": "Fermer",
    "common.back": "Retour",
    "common.next": "Suivant",
    "common.previous": "Précédent",
    "common.search": "Rechercher",
    "common.filter": "Filtrer",
    "common.sort": "Trier",
    "common.actions": "Actions",
    "common.details": "Détails",
    "common.settings": "Paramètres",
    "common.profile": "Profil",
    "common.logout": "Déconnexion",
    "common.login": "Connexion",
    "common.register": "Inscription",
    "common.required": "Requis",
    "common.optional": "Optionnel",
    "common.yes": "Oui",
    "common.no": "Non",
    "common.confirm": "Confirmer",
    "common.warning": "Attention",
    "common.info": "Information",
    "common.hero": "Héros",

    // Navigation
    "nav.dashboard": "Tableau de bord",
    "nav.tournaments": "Tournois",
    "nav.teams": "Équipes",
    "nav.players": "Joueurs",
    "nav.matches": "Matchs",
    "nav.stats": "Statistiques",
    "nav.admin": "Administration",
    "nav.heroes": "Héros",

    // Home
    "home.title": "Bienvenue sur 7ouma Ligue",
    "home.subtitle": "La plateforme complète pour gérer vos tournois de mini-foot",
    "home.description": "Organisez, gérez et suivez vos compétitions facilement",
    "home.hero.title": "Gérez vos tournois de mini-foot facilement et rapidement",
    "home.hero.subtitle": "Plateforme moderne pour organiser, suivre et vivre la passion du foot de quartier.",
    "home.hero.cta": "Découvrir les tournois",
    "home.dashboard": "Tableau de bord",
    "home.login": "Se connecter",
    "home.register": "S'inscrire",
    "home.features.title": "Tout ce dont vous avez besoin",
    "home.features.subtitle": "Une plateforme complète pour gérer votre passion du mini-foot",
    "home.features.teams": "Gestion d'équipes",
    "home.features.teams.desc": "Créez et gérez vos équipes, ajoutez des joueurs et suivez leurs performances",
    "home.features.tournaments": "Tournois",
    "home.features.tournaments.desc": "Organisez des tournois avec tirages au sort automatiques et classements",
    "home.features.matches": "Matchs",
    "home.features.matches.desc": "Planifiez vos matchs et enregistrez les résultats en temps réel",
    "home.features.stats": "Statistiques",
    "home.features.stats.desc": "Analysez les performances avec des statistiques détaillées",
    "home.features.community": "Communauté",
    "home.features.community.desc": "Connectez-vous avec d'autres passionnés de mini-foot",
    "home.features.security": "Sécurité",
    "home.features.security.desc": "Vos données sont protégées avec les dernières technologies",
    "home.stats.players": "Joueurs",
    "home.stats.teams": "Équipes",
    "home.stats.matches": "Matchs",
    "home.stats.tournaments": "Tournois",
    "home.cta.title": "Prêt à commencer ?",
    "home.cta.subtitle": "Rejoignez des milliers d'utilisateurs qui font confiance à 7ouma Ligue",
    "home.cta.start": "Commencer maintenant",
    "home.heroes.title": "Nos Héros",
    "home.heroes.subtitle": "Les meilleurs joueurs de la communauté",

    // Profile
    "profile.title": "Mon Profil",
    "profile.subtitle": "Gérez vos informations personnelles et paramètres",
    "profile.personal.info": "Informations Personnelles",
    "profile.name": "Nom complet",
    "profile.email": "Email",
    "profile.role": "Rôle",
    "profile.member.since": "Membre depuis",
    "profile.statistics": "Mes Statistiques",
    "profile.security": "Sécurité",
    "profile.quick.actions": "Actions Rapides",

    // Teams
    "teams.title": "Équipes",
    "teams.create": "Créer une équipe",
    "teams.name": "Nom de l'équipe",
    "teams.coach": "Entraîneur",
    "teams.players": "Joueurs",
    "teams.matches": "Matchs",
    "teams.wins": "Victoires",
    "teams.draws": "Nuls",
    "teams.losses": "Défaites",
    "teams.goals": "Buts",
    "teams.points": "Points",

    // Players
    "players.title": "Joueurs",
    "players.create": "Ajouter un joueur",
    "players.name": "Nom du joueur",
    "players.position": "Position",
    "players.age": "Âge",
    "players.level": "Niveau",
    "players.team": "Équipe",
    "players.jersey": "Numéro",

    // Tournaments
    "tournaments.title": "Tournois",
    "tournaments.create": "Créer un tournoi",
    "tournaments.name": "Nom du tournoi",
    "tournaments.start": "Date de début",
    "tournaments.end": "Date de fin",
    "tournaments.prize": "Prix",
    "tournaments.rules": "Règlement",
    "tournaments.teams": "équipes",
    "tournaments.groups": "Groupes",
    "tournaments.matches": "Matchs",
    "tournaments.upcoming": "À venir",
    "tournaments.active": "En cours",
    "tournaments.completed": "Terminé",
    "tournaments.details": "Détails",
    "tournaments.manage": "Gérer",
    "tournaments.draw": "Tirage",
    "tournaments.draw.title": "Tirage au sort",
    "tournaments.draw.perform": "Effectuer le tirage",
    "tournaments.draw.ai": "Tirage intelligent",
    "tournaments.draw.ai.desc": "Notre algorithme répartit équitablement les équipes",
    "tournaments.draw.balance": "Équilibrage automatique",
    "tournaments.draw.balance.desc": "Les groupes sont équilibrés selon les niveaux",
    "tournaments.draw.notPerformed": "Le tirage au sort n'a pas encore été effectué",

    // Matches
    "matches.title": "Matchs",
    "matches.create": "Créer un match",
    "matches.create.new": "Nouveau match",
    "matches.date": "Date",
    "matches.time": "Heure",
    "matches.venue": "Lieu",
    "matches.venue.placeholder": "Ex: Terrain Central",
    "matches.home.team": "Équipe domicile",
    "matches.away.team": "Équipe visiteur",
    "matches.score": "Score",
    "matches.status": "Statut",
    "matches.scheduled": "Programmé",
    "matches.live": "En cours",
    "matches.completed": "Terminé",
    "matches.error.sameTeam": "Une équipe ne peut pas jouer contre elle-même",

    // Common form fields
    "common.name": "Nom",
    "common.email": "Email",
    "common.password": "Mot de passe",
    "common.date": "Date",
    "common.time": "Heure",
    "common.venue": "Lieu",
    "common.position": "Position",
    "common.level": "Niveau",
    "common.age": "Âge",
    "common.team": "Équipe",
    "common.teams": "Équipes",
    "common.players": "Joueurs",
    "common.matches": "Matchs",
    "common.tournaments": "Tournois",
    "common.groups": "Groupes",
    "common.stats": "Statistiques",
    "common.no.team": "Aucune équipe",
    "common.select.team": "Sélectionner une équipe",
    "common.add.player": "Ajouter un joueur",
    "common.edit.player": "Modifier le joueur",
    "common.edit.match": "Modifier le match",
    "common.player.name": "Nom du joueur",
  },
  ar: {
    // Common
    "common.loading": "جاري التحميل...",
    "common.error": "خطأ",
    "common.success": "نجح",
    "common.cancel": "إلغاء",
    "common.save": "حفظ",
    "common.delete": "حذف",
    "common.edit": "تعديل",
    "common.add": "إضافة",
    "common.create": "إنشاء",
    "common.close": "إغلاق",
    "common.back": "رجوع",
    "common.next": "التالي",
    "common.previous": "السابق",
    "common.search": "بحث",
    "common.filter": "تصفية",
    "common.sort": "ترتيب",
    "common.actions": "إجراءات",
    "common.details": "تفاصيل",
    "common.settings": "إعدادات",
    "common.profile": "الملف الشخصي",
    "common.logout": "تسجيل الخروج",
    "common.login": "تسجيل الدخول",
    "common.register": "تسجيل",
    "common.required": "مطلوب",
    "common.optional": "اختياري",
    "common.yes": "نعم",
    "common.no": "لا",
    "common.confirm": "تأكيد",
    "common.warning": "تحذير",
    "common.info": "معلومات",
    "common.hero": "الأبطال",

    // Navigation
    "nav.dashboard": "لوحة التحكم",
    "nav.tournaments": "البطولات",
    "nav.teams": "الفرق",
    "nav.players": "اللاعبين",
    "nav.matches": "المباريات",
    "nav.stats": "الإحصائيات",
    "nav.admin": "الإدارة",
    "nav.heroes": "الأبطال",

    // Home
    "home.title": "مرحباً بكم في دوري الحومه ",
    "home.subtitle": "المنصة الشاملة لإدارة بطولات كرة القدم المصغرة",
    "home.description": "نظم وأدر وتابع مسابقاتك بسهولة",
    "home.hero.title": "إدارة بطولات كرة القدم المصغرة بسهولة وسرعة",
    "home.hero.subtitle": "منصة حديثة لتنظيم ومتابعة وتجربة شغف كرة القدم المصغر.",
    "home.hero.cta": "اكتشف البطولات",
    "home.dashboard": "لوحة التحكم",
    "home.login": "تسجيل الدخول",
    "home.register": "التسجيل",
    "home.features.title": "كل ما تحتاجه",
    "home.features.subtitle": "منصة شاملة لإدارة شغفك بكرة القدم المصغرة",
    "home.features.teams": "إدارة الفرق",
    "home.features.teams.desc": "أنشئ وأدر فرقك، أضف لاعبين وتابع أداءهم",
    "home.features.tournaments": "البطولات",
    "home.features.tournaments.desc": "نظم بطولات مع قرعة تلقائية وترتيب",
    "home.features.matches": "المباريات",
    "home.features.matches.desc": "خطط لمبارياتك وسجل النتائج في الوقت الفعلي",
    "home.features.stats": "الإحصائيات",
    "home.features.stats.desc": "حلل الأداء مع إحصائيات مفصلة",
    "home.features.community": "المجتمع",
    "home.features.community.desc": "تواصل مع عشاق كرة القدم المصغرة الآخرين",
    "home.features.security": "الأمان",
    "home.features.security.desc": "بياناتك محمية بأحدث التقنيات",
    "home.stats.players": "لاعب",
    "home.stats.teams": "فريق",
    "home.stats.matches": "مباراة",
    "home.stats.tournaments": "بطولة",
    "home.cta.title": "مستعد للبدء؟",
    "home.cta.subtitle": "انضم لآلاف المستخدمين الذين يثقون في دوري الحومه ",
    "home.cta.start": "ابدأ الآن",
    "home.heroes.title": "أبطالنا",
    "home.heroes.subtitle": "أفضل اللاعبين في المجتمع",

    // Teams
    "teams.title": "الفرق",
    "teams.create": "إنشاء فريق",
    "teams.name": "اسم الفريق",
    "teams.coach": "المدرب",
    "teams.players": "اللاعبون",
    "teams.matches": "المباريات",
    "teams.wins": "الانتصارات",
    "teams.draws": "التعادل",
    "teams.losses": "الهزائم",
    "teams.goals": "الأهداف",
    "teams.points": "النقاط",

    // Players
    "players.title": "اللاعبون",
    "players.create": "إضافة لاعب",
    "players.name": "اسم اللاعب",
    "players.position": "المركز",
    "players.age": "العمر",
    "players.level": "المستوى",
    "players.team": "الفريق",
    "players.jersey": "الرقم",
    "players.management": "إدارة اللاعبين",
    "players.manage.all": "إدارة جميع لاعبين الدوري",
    "players.total": "إجمالي اللاعبين",
    "players.with.team": "مع فريق",
    "players.without.team": "بدون فريق",
    "players.average.level": "متوسط المستوى",
    "players.max.level": "أعلى مستوى",
    "players.search.placeholder": "البحث عن لاعب...",
    "players.all.teams": "جميع الفرق",
    "players.all.levels": "جميع المستويات",
    "players.mass.management": "إدارة جماعية",
    "players.mass.management.desc": "استخدم هذه الأدوات لإدارة لاعبيك بكفاءة",
    "players.csv.format": "تنسيق CSV مدعوم:",
    "players.export.csv": "تصدير CSV: حفظ جميع لاعبيك",
    "players.import.csv": "استيراد CSV: تحديث جماعي",
    "players.add.player": "إضافة لاعب",
    "players.edit.player": "تعديل اللاعب",
    "players.delete.player": "حذف اللاعب",
    "players.confirm.delete": "هل أنت متأكد من حذف هذا اللاعب؟",
    "players.position.attacker": "مهاجم",
    "players.position.midfielder": "وسط",
    "players.position.defender": "مدافع",
    "players.position.goalkeeper": "حارس مرمى",
    "players.optional.team": "الفريق (اختياري)",
    "players.no.team": "بدون فريق",
    "players.optional.jersey": "رقم القميص (اختياري)",
    "players.pagination.showing": "عرض",
    "players.pagination.of": "من",
    "players.pagination.players": "لاعبين",
    "players.pagination.previous": "السابق",
    "players.pagination.next": "التالي",

    // Tournaments
    "tournaments.title": "البطولات",
    "tournaments.create": "إنشاء بطولة",
    "tournaments.name": "اسم البطولة",
    "tournaments.start": "تاريخ البداية",
    "tournaments.end": "تاريخ النهاية",
    "tournaments.prize": "الجائزة",
    "tournaments.rules": "القوانين",
    "tournaments.teams": "فرق",
    "tournaments.groups": "المجموعات",
    "tournaments.matches": "المباريات",
    "tournaments.upcoming": "قادمة",
    "tournaments.active": "جارية",
    "tournaments.completed": "منتهية",
    "tournaments.details": "التفاصيل",
    "tournaments.manage": "إدارة",
    "tournaments.draw": "القرعة",
    "tournaments.draw.title": "قرعة البطولة",
    "tournaments.draw.perform": "إجراء القرعة",
    "tournaments.draw.ai": "قرعة ذكية",
    "tournaments.draw.ai.desc": "خوارزميتنا توزع الفرق بعدالة",
    "tournaments.draw.balance": "توازن تلقائي",
    "tournaments.draw.balance.desc": "المجموعات متوازنة حسب المستويات",
    "tournaments.draw.notPerformed": "لم يتم إجراء القرعة بعد",

    // Matches
    "matches.title": "المباريات",
    "matches.create": "إنشاء مباراة",
    "matches.create.new": "مباراة جديدة",
    "matches.date": "التاريخ",
    "matches.time": "الوقت",
    "matches.venue": "المكان",
    "matches.venue.placeholder": "مثال: الملعب المركزي",
    "matches.home.team": "الفريق المضيف",
    "matches.away.team": "الفريق الضيف",
    "matches.score": "النتيجة",
    "matches.status": "الحالة",
    "matches.scheduled": "مجدولة",
    "matches.live": "جارية",
    "matches.completed": "منتهية",
    "matches.error.sameTeam": "لا يمكن للفريق أن يلعب ضد نفسه",

    // Common form fields
    "common.name": "الاسم",
    "common.email": "البريد الإلكتروني",
    "common.password": "كلمة المرور",
    "common.date": "التاريخ",
    "common.time": "الوقت",
    "common.venue": "المكان",
    "common.position": "المركز",
    "common.level": "المستوى",
    "common.age": "العمر",
    "common.team": "الفريق",
    "common.teams": "الفرق",
    "common.players": "اللاعبون",
    "common.matches": "المباريات",
    "common.tournaments": "البطولات",
    "common.groups": "المجموعات",
    "common.stats": "الإحصائيات",
    "common.no.team": "لا يوجد فريق",
    "common.select.team": "اختر فريق",
    "common.add.player": "إضافة لاعب",
    "common.edit.player": "تعديل اللاعب",
    "common.edit.match": "تعديل المباراة",
    "common.player.name": "اسم اللاعب",
  },
}

interface LanguageProviderProps {
  children: ReactNode
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<"fr" | "ar">("fr")

  const isRTL = language === "ar"

  const t = (key: string): string => {
    const languageTranslations = translations[language] as Record<string, string>
    return languageTranslations[key] || key
  }

  const value: LanguageContextType = {
    language,
    isRTL,
    setLanguage,
    t,
  }

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}
