name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      id-token: write
      contents: read

    steps:
      # 1. Récupérer le code
      - uses: actions/checkout@v3

      # 2. Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Installer les dépendances et builder ton frontend
      - name: Install and Build Frontend
        working-directory: ./7oumaligue       # Si ton frontend est à la racine, mets "."
        run: |
          npm ci
          npm run build                       # génère ./dist

      # 4. Déployer sur Azure SWA
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_TREE_0AE561303 }}
          action: upload
          app_location: "/"                   # si ton repo n'a que le frontend, sinon "./7oumaligue"
          api_location: ""                    # pas d’API Azure Functions ici
          output_location: "dist"             # dossier de build Vite

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close PR
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: close
