name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      # 1. Récupérer le code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      # 3. Installer les dépendances
      - name: Install dependencies
        run: npm ci

      # 4. Vérifier TypeScript
      - name: Type check
        run: npm run type-check

      # 5. Builder avec configuration ultra-minimale
      - name: Build Frontend
        run: npm run build:ultra

      # 6. Vérifier la structure du build
      - name: Check build output
        run: |
          echo "📁 Contenu du dossier dist:"
          ls -la dist/
          echo "📊 Taille des fichiers:"
          du -h dist/*

      # 7. Déployer sur Azure Static Web Apps
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          app_location: "/"      # frontend à la racine
          api_location: ""       # pas d'Azure Functions
          output_location: "dist" # sortie Vite
          skip_app_build: true   # on a déjà buildé
          deployment_environment: production 